spring.application.name=apron

#DB Connection 
spring.datasource.url=jdbc:mysql://localhost:3306/apron
spring.datasource.username=root
spring.datasource.password=Pulindu@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

